version: '3.3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: photodb
      POSTGRES_USER: photoapp
      POSTGRES_PASSWORD: photoapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - photo-network

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data
    networks:
      - photo-network

  backend:
    build:
      context: ./app/backend
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./app/backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/venv
    environment:
      DATABASE_URL: postgresql://photoapp:photoapp@postgres/photodb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - photo-network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=/api
      - CHOKIDAR_USEPOLLING=true  # For Windows compatibility
    depends_on:
      - backend
    networks:
      - photo-network

volumes:
  pgdata:
  redisdata:

networks:
  photo-network: 